name: gulnaz4dstem
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asteval=0.9.23
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-blosc2=2.0.4
  - ca-certificates=2022.07.19
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2022.9.24
  - cffi=1.15.0
  - cfitsio=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.10
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=36.0.1
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask=2021.12.0
  - dask-core=2021.12.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diffpy.structure=3.0.1
  - diffsims=0.4.2
  - dill=0.3.4
  - distributed=2021.12.0
  - entrypoints=0.3
  - fabio=0.12.0
  - fasteners=0.17.3
  - flit-core=3.6.0
  - freetype=2.10.4
  - fsspec=2022.1.0
  - future=0.18.2
  - giflib=5.2.1
  - glymur=0.9.7.post1
  - h5py=2.10.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - hyperspy=1.6.5
  - hyperspy-base=1.6.5
  - hyperspy-gui-ipywidgets=1.4.0
  - hyperspy-gui-traitsui=1.4.0
  - icu=58.2
  - idna=3.1
  - imagecodecs=2021.11.20
  - imageio=2.13.5
  - importlib-metadata=4.10.0
  - importlib_metadata=4.10.0
  - importlib_resources=5.4.0
  - intel-openmp=2022.0.0
  - ipyfilechooser=0.6.0
  - ipykernel=6.15.2
  - ipyparallel=8.1.0
  - ipython=7.31.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=4.3.3
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - jupyterlab_widgets=1.0.2
  - jxrlib=1.1
  - khronos-opencl-icd-loader=2022.01.04
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - link-traits=1.0.3
  - llvmlite=0.37.0
  - lmfit=1.0.3
  - locket=0.2.0
  - lxml=4.7.1
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mako=1.1.6
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - matplotlib-scalebar=0.8.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mpmath=1.2.1
  - mrcz=0.5.6
  - msgpack-python=1.0.3
  - msys2-conda-epoch=20160418
  - natsort=8.0.2
  - nbclassic=0.2.6
  - nbclient=0.5.9
  - nbconvert=6.4.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.4
  - networkx=2.6.3
  - notebook=6.4.6
  - numba=0.54.1
  - numcodecs=0.10.0
  - numexpr=2.8.1
  - numpy=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - orix=0.8.0
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pint=0.18
  - pip=21.3.1
  - pooch=1.5.2
  - prettytable=3.0.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - psutil=5.9.0
  - pycifrw=4.4.3
  - pycparser=2.21
  - pyface=7.4.1
  - pyfai-base=0.20.0
  - pygments=2.11.2
  - pyopencl=2021.2.11
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyqt=5.9.2
  - pyqt5-sip=4.19.18
  - pyreadline=2.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.9
  - python-blosc=1.10.2
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytools=2021.2.9
  - pytz=2021.3
  - pyusid=0.0.10
  - pywavelets=1.2.0
  - pywin32=303
  - pywinpty=1.1.6
  - pyxem=0.13.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - requests=2.27.1
  - scikit-image=0.18.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=59.8.0
  - setuptools-scm=6.3.2
  - sidpy=0.10
  - silx-base=1.0.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - sparse=0.13.0
  - sqlite=3.37.0
  - sympy=1.9
  - tbb=2021.5.0
  - tblib=1.7.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tifffile=2021.11.2
  - tk=8.6.11
  - tomli=2.0.0
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - traits=6.3.2
  - traitsui=7.4.0
  - transforms3d=0.3.1
  - typing_extensions=4.0.1
  - tzdata=2021e
  - ucrt=10.0.20348.0
  - uncertainties=3.1.6
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zarr=2.12.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - asciitree==0.3.3
    - efficientnet-pytorch==0.6.3
    - munch==2.5.0
    - opencv-python==4.5.5.62
    - pretrainedmodels==0.7.4
    - segmentation-models-pytorch==0.2.1
    - timm==0.4.12
    - torch==1.10.2
    - torchvision==0.11.3
